### ISSUE TITLE
Add icon to tidystats menu item

### ISSUE THREAD

**Issue by WillemSleegers** [gasparl/tidystats-Google-Docs-add-in#1]
We should add an icon (if possible) to the Insert statistics menu item. Now it looks weird with so much white space on the left.

**Comment by gasparl** [comment]
The [menu items](https://developers.google.com/apps-script/reference/base/menu#addItem(String,String)) only accept plain text, no HTML or anything else. The Google Docs editor HTML DOM [cannot be modified](https://stackoverflow.com/questions/46877859/manipulate-dom-using-google-apps-script?noredirect=1&lq=1) with GAS, only with [browser extensions](https://stackoverflow.com/a/71942167/9593181). Hence, unless we want to create browser extensions (for each major browser), the only workaround is to [use Unicode symbols](https://stackoverflow.com/a/58025046/9593181). This will however not get rid of the white space on the left, which is default for the editor, and it's occupied by icons only for some of the original Google menu items (though even Google's menu items mostly just have white space).

For now, I chose some random Unicode symbols just to test how it looks; you can change them to any other ones, or just remove them, as you prefer.

**Comment by WillemSleegers** [comment]
Thanks for looking into that. I think that means we should just get rid of the icons and accept the dumb white space. =p

**Comment by gasparl** [comment]
Ok, I removed them.
